# Generated by Django 3.1 on 2020-08-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
